# Core settings
project:
  sample_rate: 44100
  voice_samples_dir: "voice_samples"
  output_dir: "output"
  
tts:
  model: "tortoise"
  preset: "high_quality"
  vocoder: "bigvgan"

minerl:
  environment: "MineRLBasaltFindCave-v0"
  resolution: [1280, 720]
  max_duration: 600

video:
  fps: 30
  subtitle_style:
    font: "Arial"
    size: 32
    color: "#FFFFFF"
    stroke_color: "#000000"
    stroke_width: 1.5
